site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

photo_site:
    resource: "@PhotoSiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
